### ISSUE TITLE
Utils.safeString

### ISSUE THREAD

**Issue by Melindrea** [helpers/handlebars-helpers#142]
So, I've been working on a helper to create a figure as part of a gallery (probably to be used with lightboxes, etc, but this is far more generic), but I ran into an interesting issue ...

When using Utils.safeString, it still escapes the resulting HTML. Have either of you had that happen?

**Comment by mciastek** [comment]
Hi, I hope that issue is still open. I have the same problem with `Utils.safeString` like @Melindrea in `{{glob}}` helper. I'm guessing, that helper should return unescaped markup. I would use it to include svg file into template and it returns escaped string, not actual markup, as it should. I changed `return new Utils.safeString(source);` to `return new Handlebars.SafeString(source);` and it works very well.
