### ISSUE TITLE
sanitize breaks when using with grunt

### ISSUE THREAD

**Issue by stalsma** [helpers/handlebars-helpers#242]
I'm using {{sanitize}} to strip out formatting; it was working just fine at 0.6, but when I updated to 0.7.7, it quit working.

```
Running "assemble:dev" (assemble) task
Assembling out/wbt_build/wbt/lesson02/40.html ERROR
Warning: Missing helper: "sanitize" Use --force to continue.
```

I iterated over each commit, and confirmed that it broke when then dependencies were updated, that is
```
"handlebars-helpers": "https://github.com/helpers/handlebars-helpers.git#1d9852b3fbfdee7305c110eb1b6704f0e6bd372c",
```
breaks, but the previous commit does not.  This was right before 0.7.6 was released.

Strangely enough, I can use other methods from the html package (e.g. *truncate* and *ellipse*) which internally use *sanitize*.

**Comment by doowb** [comment]
@stalsma sorry we missed this issue before.

There have been many updates since then, are you still having problems? I see that the `sanitize` helper is there.

I'm going to close this, but if you're still having issues will you make a new issue? If this is specific to [grunt-assemble](https://github.com/assemble/grunt-assemble), please open an issue there.
