### ISSUE TITLE
ES6 + Brunch

### ISSUE THREAD

**Issue by 3nvy** [helpers/handlebars-helpers#270]
So, I have a project using ES6 + Brunch.io but I'm having trouble getting handlebars-helpers to work :s 
Im also using 'handlebars-brunch', dont know if theres a way to integrate with it or a better plugin.

Does anyone knows a way to do it?

Best Regards

**Comment by doowb** [comment]
If you have code examples on how you've tried to use it and post any errors that are occurring due to `handlebars-helpers` failing, it will help us understand if this is a bug here or not. Also, if this is a general support question, you should post it on stack overflow with tags that will get more eyes on the issue. Feel free to post the stack overflow link here.

Personally, I haven't used `brunch` so I'm not sure where to start looking.

**Comment by 3nvy** [comment]
@doowb thks for the reply ;)

I was able to archive what I wanted. I forgot about the brunch plugin as it probably doesnt support helpers yet. So I decided to pre-compile the templates with npm scripts prior to brunch bundle and it works perfectly :D

**Comment by jonschlinkert** [comment]
great, glad you found a solution!
