### ISSUE TITLE
`.length` is returned invalid length of the string.

### ISSUE THREAD

**Issue by why2pac** [helpers/handlebars-helpers#271]
```node
{{length "my[string]"}}
```

Upper code is return 0.

It is because the `.length` helper try parse to object.

```node
if (typeof value === 'string' && /[[]/.test(value)) {
    value = utils.tryParse(value) || [];
  }
```

This issue is in line with #269.

**Comment by doowb** [comment]
As a workaround, you can use `split` as a subexpression:

```handlebars
{{length (split "my[string]" "")}}
```

`length` is documented saying that if a string is passed that will attempt to parse it into an array.
It doesn't explicitly say that it will return the length of a string and it is in the `collections` collection.

I think in this case a `strlen` helper would be useful since it will disambiguate getting the length of a collection (array or object keys), and the length of a string. This will keep `handlebars-helpers` backward compatible and only require a patch bump.

The other option is to not parse strings and just return their length. This would be a breaking change and require a minor bump.

If anyone else has any thoughts on this, please let us know. Otherwise, we'll go with adding `strlen`.
