### ISSUE TITLE
Handlebars utils IE11 error

### ISSUE THREAD

**Issue by mikeebee** [helpers/handlebars-helpers#286]
Hi there,

I've noticed that the `expectedType` function from the included Handlebars Utils is causing issues in IE11 due to the usage of template literals.

https://github.com/helpers/handlebars-utils/blob/master/index.js - line 136 

I am using Babel to transpile my JavaScript, (including template literals) but these files obviously aren't being being affected because they are in the node_modules folder (expected behaviour).

There may be other issues as well but this is the one it's breaking on currently.

Can you offer any advice on how to circumvent this?

Many thanks

handlebars-helpers version 0.9.7

**Comment by doowb** [comment]
@mikeebee thanks for the issue.

This library (`handlebars-helpers`) specifies that it supports node.js versions 5 and up in the package.json `engine` property. And `handlebars-utils` specifies versions 4 and up.

If you need to support older JavaScript engines, you should transpile the dependencies, that might have newer features, along with your app source code. I think with WebPack you can specify glob patterns for loaders, I'm not sure if there's a way to directly specify dependencies to transpile in Babel.

Another option is to do a PR to `handlebars-utils` to add a transpile step to generate a browser version of the file and configure the `package.json` so that the browser version will work with Babel, browserify, WebPack, Rollup, etc... (I don't know all the configuration that is necessary for it to work with all of the bundlers).

We use these libraries too (mostly in node.js) and want to make sure they work in a wide range of environments, but sometimes there are environments that we don't use and need help supporting, so a PR would be greatly appreciated.

**Comment by mikeebee** [comment]
@doowb thanks for the feedback, this was very helpful. 

It turned out that both `handlebars-utils` and `striptags` were both causing issues. For `handlebars-utils` I added a project specific fix that will work with Babelify, and used an earlier version of `striptags` as a temporary measure. If I manage to create a comprehensive solution that will work across bundlers I will open a PR.

Many thanks!

**Comment by jonschlinkert** [comment]
closing, sounds like this is resolved for now

**Comment by doowb** [comment]
no problem @mikeebee. I'm glad you found a configuration that works.

**Comment by rafegoldberg** [comment]
@mikeebee I'm having the same issue with the `handlebars-utils` template literal throwing an error in IE. How did you change your Babelify config to fix this?
