### ISSUE TITLE
Does the project support node's 'async'?

### ISSUE THREAD

**Issue by mrself** [helpers/handlebars-helpers#352]
I want to make a pull request for one helper `url-inject`. I want it to insert content from URL into html. However requests in node are async but as I see all helpers are sync. What should I do?

**Comment by doowb** [comment]
If you're using `handlebars-helpers` directly in `handlebars` then the helpers need to be sync because `handlebars` doesn't handle async helpers.

If you're using another library that supports async helpers, then you should check with that library on how to add the async helpers.

If you have additional code on how you're using your helpers, please post it here and someone might be able to help.

**Comment by mrself** [comment]
The code is pretty simple:

```
'use strict';

var http = require('http');

module.exports.urlInject = function (url) {
    http.get(url, function (response) {
        var data = '';
        response.on('data', function (chunk) {
            data += chunk;
        });
        response.on('end', function () {
            // Here data is ready, need to return it in sync.
        });
    });
};
```

**Comment by doowb** [comment]
I meant, where are you using it?

The `handlebars` template engine doesn't handle async helpers.

**Comment by mrself** [comment]
I currently have no related code as I do not what I need to start with. I use an ecommerce platform which does not provide an access to server code. The only thing I can alter is templates in handlebars. They told me that I can create new helper which suits my needs and they will connect it.

However, now I see that it is not so easy task and I can not find a solution for this. I considered using `fs` helper. But the platform restricts template size to 50 MB.

**Comment by doowb** [comment]
Thanks for the additional information. Did they tell you that you can make an async helper? If so, you can create your new helper based on what you did above and however they handle async helpers.

We won't be able to accept any async helpers into this library (`handlebars-helpers`) at this time since these are for using in `handlebars`, which doesn't support async helpers.

**Comment by mrself** [comment]
We did not talk about my helper. They just redirected me to this package.

I see that this package does not support async helpers. I tried to find a package which makes sync http requests but no luck. Anyway, thanks for your quick response.
